title: "Shiv Vyas Portfolio - Space Edition"
description: "Quantitative Researcher | AI & Data Science Expert | Journey Through the Cosmos of Data"
theme: jekyll-theme-minimal
source: ./docs
markdown: kramdown

# Social Links (Used in the footer or social icons)
social:
  github: "https://github.com/svyas19"
  linkedin: "https://linkedin.com/in/shivvyas"
  email: "shiv@example.com"

# Enable pagination (optional if you need for blogs or posts)
paginate: 5

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - docs/assets/icons/*

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist

kramdown:
  input: GFM
